[package]
name    = "temenos-identity"
version = "0.1.0"
authors = [ "pcummuskey <peterc@aetheric.co.nz>" ]
build   = "build.rs"

[build-dependencies]
kafka       = "*"
openssl     = "*"
protoc-rust = "*"

[dependencies]
protoc = "*"
